//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication1.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PhisicalDrive", Namespace="http://schemas.datacontract.org/2004/07/HDDInfo")]
    [System.SerializableAttribute()]
    public partial class PhisicalDrive : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CaptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DeviceIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SizeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StatusField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Caption {
            get {
                return this.CaptionField;
            }
            set {
                if ((object.ReferenceEquals(this.CaptionField, value) != true)) {
                    this.CaptionField = value;
                    this.RaisePropertyChanged("Caption");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DeviceID {
            get {
                return this.DeviceIDField;
            }
            set {
                if ((object.ReferenceEquals(this.DeviceIDField, value) != true)) {
                    this.DeviceIDField = value;
                    this.RaisePropertyChanged("DeviceID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Size {
            get {
                return this.SizeField;
            }
            set {
                if ((object.ReferenceEquals(this.SizeField, value) != true)) {
                    this.SizeField = value;
                    this.RaisePropertyChanged("Size");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Status {
            get {
                return this.StatusField;
            }
            set {
                if ((object.ReferenceEquals(this.StatusField, value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MyObject", Namespace="http://schemas.datacontract.org/2004/07/HDDInfo")]
    [System.SerializableAttribute()]
    public partial class MyObject : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CaptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DeviceIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WindowsFormsApplication1.ServiceReference1.MyObject2[] LogicalDrivesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SizeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StatusField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Caption {
            get {
                return this.CaptionField;
            }
            set {
                if ((object.ReferenceEquals(this.CaptionField, value) != true)) {
                    this.CaptionField = value;
                    this.RaisePropertyChanged("Caption");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DeviceID {
            get {
                return this.DeviceIDField;
            }
            set {
                if ((object.ReferenceEquals(this.DeviceIDField, value) != true)) {
                    this.DeviceIDField = value;
                    this.RaisePropertyChanged("DeviceID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WindowsFormsApplication1.ServiceReference1.MyObject2[] LogicalDrives {
            get {
                return this.LogicalDrivesField;
            }
            set {
                if ((object.ReferenceEquals(this.LogicalDrivesField, value) != true)) {
                    this.LogicalDrivesField = value;
                    this.RaisePropertyChanged("LogicalDrives");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Size {
            get {
                return this.SizeField;
            }
            set {
                if ((object.ReferenceEquals(this.SizeField, value) != true)) {
                    this.SizeField = value;
                    this.RaisePropertyChanged("Size");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Status {
            get {
                return this.StatusField;
            }
            set {
                if ((object.ReferenceEquals(this.StatusField, value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MyObject2", Namespace="http://schemas.datacontract.org/2004/07/HDDInfo")]
    [System.SerializableAttribute()]
    public partial class MyObject2 : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DeviceIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DriveFormatField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DriveTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FreeSpacePercentsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FreeSpaceTotalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TotalSizeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ValumeLabelField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DeviceID {
            get {
                return this.DeviceIDField;
            }
            set {
                if ((object.ReferenceEquals(this.DeviceIDField, value) != true)) {
                    this.DeviceIDField = value;
                    this.RaisePropertyChanged("DeviceID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DriveFormat {
            get {
                return this.DriveFormatField;
            }
            set {
                if ((object.ReferenceEquals(this.DriveFormatField, value) != true)) {
                    this.DriveFormatField = value;
                    this.RaisePropertyChanged("DriveFormat");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DriveType {
            get {
                return this.DriveTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.DriveTypeField, value) != true)) {
                    this.DriveTypeField = value;
                    this.RaisePropertyChanged("DriveType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FreeSpacePercents {
            get {
                return this.FreeSpacePercentsField;
            }
            set {
                if ((object.ReferenceEquals(this.FreeSpacePercentsField, value) != true)) {
                    this.FreeSpacePercentsField = value;
                    this.RaisePropertyChanged("FreeSpacePercents");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FreeSpaceTotal {
            get {
                return this.FreeSpaceTotalField;
            }
            set {
                if ((object.ReferenceEquals(this.FreeSpaceTotalField, value) != true)) {
                    this.FreeSpaceTotalField = value;
                    this.RaisePropertyChanged("FreeSpaceTotal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TotalSize {
            get {
                return this.TotalSizeField;
            }
            set {
                if ((object.ReferenceEquals(this.TotalSizeField, value) != true)) {
                    this.TotalSizeField = value;
                    this.RaisePropertyChanged("TotalSize");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ValumeLabel {
            get {
                return this.ValumeLabelField;
            }
            set {
                if ((object.ReferenceEquals(this.ValumeLabelField, value) != true)) {
                    this.ValumeLabelField = value;
                    this.RaisePropertyChanged("ValumeLabel");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IHddInfo")]
    public interface IHddInfo {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHddInfo/GetHddInfo", ReplyAction="http://tempuri.org/IHddInfo/GetHddInfoResponse")]
        WindowsFormsApplication1.ServiceReference1.PhisicalDrive[] GetHddInfo();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHddInfo/GetHddInfo", ReplyAction="http://tempuri.org/IHddInfo/GetHddInfoResponse")]
        System.Threading.Tasks.Task<WindowsFormsApplication1.ServiceReference1.PhisicalDrive[]> GetHddInfoAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHddInfo/Test", ReplyAction="http://tempuri.org/IHddInfo/TestResponse")]
        string Test();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHddInfo/Test", ReplyAction="http://tempuri.org/IHddInfo/TestResponse")]
        System.Threading.Tasks.Task<string> TestAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHddInfo/TestMyObject", ReplyAction="http://tempuri.org/IHddInfo/TestMyObjectResponse")]
        WindowsFormsApplication1.ServiceReference1.MyObject[] TestMyObject();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHddInfo/TestMyObject", ReplyAction="http://tempuri.org/IHddInfo/TestMyObjectResponse")]
        System.Threading.Tasks.Task<WindowsFormsApplication1.ServiceReference1.MyObject[]> TestMyObjectAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IHddInfoChannel : WindowsFormsApplication1.ServiceReference1.IHddInfo, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class HddInfoClient : System.ServiceModel.ClientBase<WindowsFormsApplication1.ServiceReference1.IHddInfo>, WindowsFormsApplication1.ServiceReference1.IHddInfo {
        
        public HddInfoClient() {
        }
        
        public HddInfoClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public HddInfoClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HddInfoClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HddInfoClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public WindowsFormsApplication1.ServiceReference1.PhisicalDrive[] GetHddInfo() {
            return base.Channel.GetHddInfo();
        }
        
        public System.Threading.Tasks.Task<WindowsFormsApplication1.ServiceReference1.PhisicalDrive[]> GetHddInfoAsync() {
            return base.Channel.GetHddInfoAsync();
        }
        
        public string Test() {
            return base.Channel.Test();
        }
        
        public System.Threading.Tasks.Task<string> TestAsync() {
            return base.Channel.TestAsync();
        }
        
        public WindowsFormsApplication1.ServiceReference1.MyObject[] TestMyObject() {
            return base.Channel.TestMyObject();
        }
        
        public System.Threading.Tasks.Task<WindowsFormsApplication1.ServiceReference1.MyObject[]> TestMyObjectAsync() {
            return base.Channel.TestMyObjectAsync();
        }
    }
}
